version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-django
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
